Decaffeinate
Tabcorp/bitmap-integers pull request #2
Opened 2021-07-13 22:13 UTC by deancouch

Cleanup

- decaffeinate
- travis update
- updated dependencies

2021-07-13 23:13 UTC, vickvu requested changes
There are also a lot of `function(){` that can be changed to `()=>` and unnecessary `return` in the test files but they are not that important 😄

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +        return bitmap.value += Math.pow(2, (Math.floor(value)) - 1);
You can remove unnecessary return
```suggestion
        bitmap.value += Math.pow(2, (Math.floor(value)) - 1);
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +    return function(bitmap, value, index) {
You can use `=>` here
```suggestion
  return getValue(_.uniq(integerArray), 'number', (bitmap, value, index) => {
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +  })(this));
```suggestion
    });
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +  return getValue(booleanArray, 'boolean', function(bitmap, value, index) {
and here
```suggestion
  return getValue(booleanArray, 'boolean', (bitmap, value, index) => {
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +      return bitmap.value += Math.pow(2, index);
here as well
```suggestion
      bitmap.value += Math.pow(2, index);
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +  return getValue(booleanArray, 'boolean', function(bitmap, value, index) {
same here
```suggestion
  return getValue(booleanArray, 'boolean', (bitmap, value, index) => {
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +      return bitmap.value += Math.pow(2, index);
```suggestion
      bitmap.value += Math.pow(2, index);
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +  return invalidValue === void 0;
use findIndex and avoid lodash as array must be an instance of Array class, all in one line
```suggestion
  return array.findIndex((value) => typeof value !== valueType) < 0;
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +  _(array).forEach(function(value, index) {
No need to use lodash here (array must be an instance of Array class in `validArray` function)
```suggestion
  array.forEach((value, index) => {
```

2021-07-13 23:13 UTC, vickvu commented on src/array-to-integer.js
> +    return callback(bitmap, value, index);
Remove return
```suggestion
    callback(bitmap, value, index);
```

2021-07-13 23:13 UTC, vickvu commented on src/bitmap.js
> +const _ = require('lodash');
no need to have lodash here
```suggestion
```

2021-07-13 23:13 UTC, vickvu commented on src/integer-to-array.js
> +      return result.push(index + 1);
```suggestion
      result.push(index + 1);
```

2021-07-13 23:13 UTC, vickvu commented on src/integer-to-array.js
> +    return result.push(character === '1' ? true : false);
```suggestion
  return getArray(value, (result, character, index) => {
    result.push(character === '1' ? true : false);
```

2021-07-13 23:13 UTC, vickvu commented on src/integer-to-array.js
> +    return callback(result, character, index);
```suggestion
  Math.floor(value).toString(2).split('').reverse().forEach((character, index) => {
    callback(result, character, index);
```

2021-07-14 00:24 UTC, nizhu commented on .travis.yml
> +  - "16"
huuuge upgrade

2021-07-14 00:25 UTC, nizhu approved these changes
can replace vick with eslint

2021-07-14 14:13 UTC, vickvu approved these changes

2021-07-14 22:45 UTC, merged